# Generated by Django 2.1.7 on 2019-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190328_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
