# Generated by Django 2.1.7 on 2019-04-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190425_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='idFakultas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Fakultas'),
        ),
    ]
