# Generated by Django 2.1.7 on 2019-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190425_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='namaJurusan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
