# Generated by Django 2.2 on 2019-05-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190425_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='papi.BidangPKM'),
        ),
    ]
