# Generated by Django 2.2 on 2019-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190505_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papi.BidangPKM'),
        ),
    ]
