# Generated by Django 2.2 on 2019-05-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190505_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papi.KategoriPKM'),
        ),
    ]
