# Generated by Django 2.2.1 on 2019-06-01 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0034_auto_20190601_2254'),
        ('bempapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatproposalpkm',
            name='namaBidang',
        ),
        migrations.AddField(
            model_name='formatproposalpkm',
            name='bidangPKM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papi.BidangPKM'),
        ),
    ]
