# Generated by Django 2.1.7 on 2019-04-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0002_proposalpkm_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpkm',
            name='idKategori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papi.KategoriPKM'),
        ),
    ]
