# Generated by Django 2.1.7 on 2019-04-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0007_proposalpkm_idstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalpkm',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='proposalpkm',
            name='status',
        ),
    ]
