# Generated by Django 2.1.7 on 2019-04-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0010_anggota_idketua'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='idPkm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papi.ProposalPKM'),
        ),
    ]
