# Generated by Django 2.1.7 on 2019-04-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papi', '0011_anggota_idpkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistoryPKM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkRevisi', models.CharField(max_length=100)),
                ('idKetua', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idStatus', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papi.StatusRevisi')),
            ],
        ),
    ]
