# Generated by Django 2.1.7 on 2019-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0012_loghistorypkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='npmAnggota',
            field=models.CharField(default='', max_length=13),
        ),
    ]
