# Generated by Django 2.1.7 on 2019-04-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0014_auto_20190410_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='idKetua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='idPkm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papi.ProposalPKM'),
        ),
        migrations.AlterField(
            model_name='loghistorypkm',
            name='idKetua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loghistorypkm',
            name='idStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papi.StatusRevisi'),
        ),
    ]
