# Generated by Django 2.1.7 on 2019-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0016_cobamultipleinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpkm',
            name='deskripsi',
            field=models.CharField(default='', max_length=200),
        ),
    ]
