# Generated by Django 2.1.7 on 2019-04-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190425_2101'),
        ('papi', '0019_auto_20190424_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpkm',
            name='idFakultas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Fakultas'),
        ),
    ]
