# Generated by Django 2.2 on 2019-05-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0020_proposalpkm_idfakultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalpkm',
            name='idBidang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papi.BidangPKM'),
        ),
        migrations.AlterField(
            model_name='proposalpkm',
            name='idFakultas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Fakultas'),
        ),
        migrations.AlterField(
            model_name='proposalpkm',
            name='idKategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papi.KategoriPKM'),
        ),
        migrations.AlterField(
            model_name='proposalpkm',
            name='idStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papi.StatusRevisi'),
        ),
    ]
