# Generated by Django 2.2 on 2019-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0022_proposalpkm_iddosenreviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistorypkm',
            name='document',
            field=models.FileField(default='ProposalDefault.txt', upload_to='proposalrevisi'),
        ),
    ]
