# Generated by Django 2.2 on 2019-05-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190505_2351'),
        ('papi', '0023_loghistorypkm_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghistorypkm',
            name='linkRevisi',
        ),
        migrations.AddField(
            model_name='loghistorypkm',
            name='idDosenReviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Dosen'),
        ),
    ]
