# Generated by Django 2.2 on 2019-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0024_auto_20190509_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistorypkm',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papi.ProposalPKM'),
        ),
    ]
