# Generated by Django 2.2 on 2019-05-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0026_remove_anggota_idpkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='idKetua',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
