# Generated by Django 2.2 on 2019-05-20 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0027_auto_20190520_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalpkm',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
