# Generated by Django 2.2 on 2019-05-20 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papi', '0028_proposalpkm_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenPembimbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaDosen', models.CharField(max_length=20)),
                ('nipDosen', models.CharField(default='', max_length=13)),
                ('emailDosen', models.EmailField(max_length=254, null=True)),
                ('idKetua', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
