# Generated by Django 2.2.1 on 2019-06-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0029_dosenpembimbing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loghistorypkm',
            old_name='document',
            new_name='idProposalPkm',
        ),
    ]
