# Generated by Django 2.2.1 on 2019-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0030_auto_20190601_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistorypkm',
            name='documentRevisi',
            field=models.FileField(default='ProposalDefault.txt', upload_to='revisi'),
        ),
    ]
