# Generated by Django 2.2.1 on 2019-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0032_remove_loghistorypkm_idstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghistorypkm',
            name='deskripsiLog',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loghistorypkm',
            name='documentRevisi',
            field=models.FileField(default='ProposalDefault.txt', null=True, upload_to='revisi'),
        ),
    ]
