# Generated by Django 2.2.1 on 2019-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0033_auto_20190601_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistorypkm',
            name='documentRevisi',
            field=models.FileField(null=True, upload_to='revisi'),
        ),
    ]
