# Generated by Django 2.2.4 on 2019-12-13 17:01

from django.db import migrations, models
import papi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0034_auto_20190601_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistorypkm',
            name='documentRevisi',
            field=models.FileField(null=True, upload_to='revisi', validators=[papi.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='proposalpkm',
            name='document',
            field=models.FileField(default='DefaultFile.docx', upload_to='proposal', validators=[papi.validators.validate_file_extension]),
        ),
    ]
