# Generated by Django 2.2.4 on 2019-12-13 17:09

from django.db import migrations, models
import papi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0035_auto_20191214_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistorypkm',
            name='documentRevisi',
            field=models.FileField(default='DefaultFile.docx', upload_to='revisi', validators=[papi.validators.validate_file_extension]),
        ),
    ]
